version = 1

exclude_patterns = ["/**/*.stories.tsx", "/scores/**"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
