FROM node:16-slim AS build
ENV CI=true
RUN apt-get update && apt-get install build-essential python3 -y

WORKDIR /app
COPY .yarnrc.yml /app/
COPY .yarn /app/.yarn

COPY package.json /app/
COPY scores-src/package.json /app/scores-src/
COPY bundle-src/package.json /app/bundle-src/
COPY yarn.lock /app/

RUN yarn --immutable --inline-builds && rm .yarn/cache/*
