ARG NODECG_VERSION=1.8.1
FROM registry.comp.ystv.co.uk/nodecg/nodecg:v${NODECG_VERSION} AS build
ENV CI=true
RUN apt-get update && apt-get install build-essential python3 -y

WORKDIR /app
COPY .yarnrc.yml /app/
COPY .yarn /app/.yarn

COPY patches/ /app/patches/
COPY package.json /app/
COPY scores-src/package.json /app/scores-src/
COPY bundle-src/package.json /app/bundle-src/
COPY yarn.lock /app/

RUN yarn --immutable --inline-builds && rm .yarn/cache/*
