version: '3.9'
services:
  couchbase:
    image: couchbase/server:community-7.0.2
    volumes:
      - cbdata:/cbdata
    ports:
      - "8091-8097:8091-8097"
      - "11210-11211:11210-11211"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
  
  redis:
    image: redis:6-alpine

volumes:
  cbdata:
