version: '3.9'
services:

  server:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/nodecg/bundles/ystv-sports-graphics:cached
      - .devcontainer/bundle-config.json:/nodecg/cfg/ystv-sports-graphics.json
      - .devcontainer/nodecg-config.json:/nodecg/cfg/nodecg.json
      - vscode-cache:/home/vscode/.vscode-server/extensions
      - vscode-insiders-cache:/home/vscode/.vscode-server-insiders/extensions
      - yarn-cache:/nodecg/bundles/ystv-sports-graphics/.yarn/cache
    working_dir: /nodecg/bundles/ystv-sports-graphics
    command: sleep 9999999999
    ports:
      - 9090:9090
      - 8082:8082
  
  nodecg:
    profiles:
      - donotstart

volumes:
  vscode-cache:
  vscode-insiders-cache:
  yarn-cache:
