name: End-to-End Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cypress:
    strategy:
      matrix:
        component: [bundle, scores]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout NodeCG
        uses: actions/checkout@v3
        with:
          repository: ystv/nodecg
          ref: ystv
          path: ./nodecg

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./nodecg/bundles/ystv-sports-graphics

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: ./nodecg/bundles/ystv-sports-graphics
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock,**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --immutable --inline-builds
        working-directory: ./nodecg/bundles/ystv-sports-graphics

      - name: Build app
        working-directory: ./nodecg/bundles/ystv-sports-graphics/scores-src
        env:
          NODE_ENV: test
        run: |
          yarn build
          mkdir -p build/Release/
          cp ../node_modules/couchbase/build/Release/couchbase_impl.node build/Release/couchbase_impl.node

      - name: Install NodeCG dependencies
        if: matrix.component == 'bundle'
        working-directory: ./nodecg
        run: npm ci

      - name: Start everything!
        run: nodecg/bundles/ystv-sports-graphics/scripts/test-e2e.sh --setup-only

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          spec: ${{ matrix.component }}-src/**
          working-directory: ./nodecg/bundles/ystv-sports-graphics
          group: ${{ matrix.component }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # overwrite commit message sent to Cypress Cloud
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          # re-enable PR comment bot
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}

      - name: Upload videos of failures
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: E2E test video
          path: ./nodecg/bundles/ystv-sports-graphics/cypress/videos

      - name: Upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Server logs
          path: |
            ./nodecg/bundles/ystv-sports-graphics/test-server.log
            ./nodecg/bundles/ystv-sports-graphics/test-nodecg.log
