# This is a basic workflow to help you get started with Actions

name: Run unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout NodeCG
        uses: actions/checkout@v3
        with:
          repository: ystv/nodecg
          ref: ystv
          path: ./nodecg

      - uses: actions/checkout@v3
        with:
          path: ./nodecg/bundles/ystv-sports-graphics

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: ./nodecg/bundles/ystv-sports-graphics
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock,**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        working-directory: ./nodecg/bundles/ystv-sports-graphics
        run: yarn --immutable --inline-builds

      - name: Run unit tests
        run: nodecg/bundles/ystv-sports-graphics/scripts/test-unit.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          root_dir: ./nodecg/bundles/ystv-sports-graphics
          files: scores-src/src/common/coverage/clover.xml,scores-src/src/server/coverage/clover.xml,scores-src/src/client/coverage/clover.xml
          gcov_ignore: ./nodecg/bundles/ystv-sports-graphics/.yarn

  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout NodeCG
        uses: actions/checkout@v3
        with:
          repository: ystv/nodecg
          ref: ystv
          path: ./nodecg

      - uses: actions/checkout@v3
        with:
          path: ./nodecg/bundles/ystv-sports-graphics

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: ./nodecg/bundles/ystv-sports-graphics
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock,**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        working-directory: ./nodecg/bundles/ystv-sports-graphics
        run: yarn --immutable --inline-builds

      - name: Run integration tests
        run: nodecg/bundles/ystv-sports-graphics/scripts/test-integration.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          root_dir: ./nodecg/bundles/ystv-sports-graphics
          files: scores-src/src/common/coverage/clover.xml,scores-src/src/server/coverage/clover.xml,scores-src/src/client/coverage/clover.xml
          gcov_ignore: ./nodecg/bundles/ystv-sports-graphics/.yarn
